from typing import Any, Dict, Iterator, TypeVar
from typing_extensions import Protocol
T = TypeVar('T')
def __iter__(self) ->'Iterator[IRow]':...
...
def filter(self, expression: bool) ->bool:...
...
def __getattr__(self, name: str) ->Any:...
...
def __iter__(self) ->Iterator[IRow]:...
...
selected_fields: 'Dict[str, ISpy]'
is_subquery: bool
name: str
def query(self, query_string: str) ->Iterator[IRow]:...
...
