def _generate_groups(self, profile):...
if not profile:
return {}
def group_entry(group):...
return {'id': group.id, 'size': group.members.count(), 'collaborators':
    group.collaborator_names(profile)}
