def get_bookmark_parameters(self, bookmark):...
"""docstring"""
def __init__(self, dirstructure):...
self._store = []
self._ds = dirstructure
def does_intersect_rule(self, rulectx):...
return bookmark in rulectx.bookmarks
