def __repr__(self):...
return f'{self.__class__.__name__}(chat_id={self.chat_id}, first_name="{self.first_name}", nickname="{self.nickname}", last_name="{self.last_name}", language="{self.language}")'
