"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os
from datetime import timedelta
from django.utils.translation import gettext_lazy as _
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SETTINGS_PATH = os.path.normpath(os.path.dirname(__file__))
SECRET_KEY = '_dzlo^9d#ox6!7c9rju@=u8+4^sprqocy3s*l*ejc2yr34@&98'
DEBUG = True
ALLOWED_HOSTS = []
INSTALLED_APPS = ['constance', 'constance.backends.database',
    'jet.dashboard', 'jet', 'import_export', 'django.contrib.admin',
    'django.contrib.auth', 'django.contrib.contenttypes',
    'django.contrib.sessions', 'django.contrib.messages',
    'django.contrib.staticfiles', 'django.contrib.humanize',
    'django_celery_beat', 'compressor', 'websecmap.app',
    'websecmap.organizations', 'websecmap.scanners', 'websecmap.reporting',
    'websecmap.map', 'websecmap.pro', 'dashboard.internet_nl_dashboard',
    'django_otp', 'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp', 'two_factor']
if not os.environ.get('COMPRESS', False):
MIDDLEWARE = ['django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware']
import django_uwsgi
ROOT_URLCONF = 'dashboard.urls'
INSTALLED_APPS += ['django_uwsgi']
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR + '/'], 'APP_DIRS': True, 'OPTIONS': {
    'context_processors': ['constance.context_processors.config',
    'django.template.context_processors.debug',
    'django.template.context_processors.request',
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages']}}]
WSGI_APPLICATION = 'dashboard.wsgi.application'
DATABASE_OPTIONS = {'mysql': {'init_command':
    "SET character_set_connection=utf8,collation_connection=utf8_unicode_ci,sql_mode='STRICT_ALL_TABLES';"
    }}
DB_ENGINE = os.environ.get('DB_ENGINE', 'mysql')
DATABASE_ENGINES = {'mysql': 'dashboard.app.backends.mysql'}
DATABASES_SETTINGS = {'dev': {'ENGINE': 'django.db.backends.sqlite3',
    'NAME': os.environ.get('DB_NAME', 'db.sqlite3')}, 'test': {'ENGINE':
    'django.db.backends.sqlite3', 'NAME': os.environ.get('DB_NAME',
    'db.sqlite3')}, 'production': {'ENGINE': DATABASE_ENGINES.get(DB_ENGINE,
    'django.db.backends.' + DB_ENGINE), 'NAME': os.environ.get('DB_NAME',
    'dashboard'), 'USER': os.environ.get('DB_USER', 'dashboard'),
    'PASSWORD': os.environ.get('DB_PASSWORD', 'dashboard'), 'HOST': os.
    environ.get('DB_HOST', 'mysql'), 'OPTIONS': DATABASE_OPTIONS.get(os.
    environ.get('DB_ENGINE', 'mysql'), {})}}
DATABASE = os.environ.get('DJANGO_DATABASE', 'dev')
DATABASES = {'default': DATABASES_SETTINGS[DATABASE]}
AUTH_PASSWORD_VALIDATORS = [{'NAME':
    'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
    }, {'NAME':
    'django.contrib.auth.password_validation.MinimumLengthValidator'}, {
    'NAME':
    'django.contrib.auth.password_validation.CommonPasswordValidator'}, {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}
    ]
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
LOCALE_PATHS = ['locale']
LANGUAGE_COOKIE_NAME = 'dashboard_language'
STATIC_URL = '/static/'
if DEBUG:
STATIC_ROOT = 'static'
STATIC_ROOT = '/srv/dashboard/static/'
JET_SIDE_MENU_ITEMS = [{'label': _('🔧 Configuration'), 'items': [{'name':
    'auth.user'}, {'name': 'auth.group'}, {'name': 'constance.config',
    'label': _('Configuration')}]}, {'label': _('Dashboard'), 'items': [{
    'name': 'internet_nl_dashboard.account'}, {'name':
    'internet_nl_dashboard.urllist'}, {'name':
    'internet_nl_dashboard.uploadlog'}]}, {'label': _('🕒 Periodic Tasks'),
    'items': [{'name': 'app.job'}, {'name':
    'django_celery_beat.periodictask'}, {'name':
    'django_celery_beat.crontabschedule'}]}]
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.abspath(os.path.dirname(
    __file__)) + '/uploads/')
UPLOAD_ROOT = os.environ.get('MEDIA_ROOT', os.path.abspath(os.path.dirname(
    __file__)) + '/uploads/')
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = LOGIN_URL
TWO_FACTOR_QR_FACTORY = 'qrcode.image.pil.PilImage'
TWO_FACTOR_TOTP_DIGITS = 6
TWO_FACTOR_PATCH_ADMIN = True
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY',
    b'JjvHNnFMfEaGd7Y0SAHBRNZYGGpNs7ydEp-ixmKSvkQ=')
if not DEBUG and FIELD_ENCRYPTION_KEY == b'JjvHNnFMfEaGd7Y0SAHBRNZYGGpNs7ydEp-ixmKSvkQ=':
LOGGING = {'version': 1, 'disable_existing_loggers': False, 'handlers': {
    'console': {'class': 'logging.StreamHandler', 'formatter': 'color'}},
    'formatters': {'debug': {'format':
    '%(asctime)s\t%(levelname)-8s - %(filename)-20s:%(lineno)-4s - %(funcName)20s() - %(message)s'
    }, 'color': {'()': 'colorlog.ColoredFormatter', 'format':
    '%(log_color)s%(asctime)s\t%(levelname)-8s - %(message)s', 'datefmt':
    '%Y-%m-%d %H:%M', 'log_colors': {'DEBUG': 'green', 'INFO': 'white',
    'WARNING': 'yellow', 'ERROR': 'red', 'CRITICAL': 'bold_red'}}},
    'loggers': {'django': {'handlers': ['console'], 'level': os.getenv(
    'DJANGO_LOG_LEVEL', 'INFO')}, 'dashboard': {'handlers': ['console'],
    'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG')}}}
CELERY_accept_content = ['pickle', 'yaml']
CELERY_task_serializer = 'pickle'
CELERY_result_serializer = 'pickle'
CELERY_BROKER_URL = os.environ.get('BROKER', 'redis://localhost:6379/0')
ENABLE_UTC = True
CELERY_ACCEPT_CONTENT = ['pickle']
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_TIMEZONE = 'UTC'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BROKER_CONNECTION_MAX_RETRIES = 1
CELERY_BROKER_CONNECTION_RETRY = False
CELERY_RESULT_EXPIRES = timedelta(hours=4)
CELERY_WORKER_PREFETCH_MULTIPLIER = 2
CELERY_WORKER_CONCURRENCY = 10
CELERY_ACKS_LATE = True
TOOLS = {'organizations': {'import_data_dir': ''}}
OUTPUT_DIR = os.environ.get('OUTPUT_DIR', os.path.abspath(os.path.dirname(
    __file__)) + '/')
VENDOR_DIR = os.environ.get('VENDOR_DIR', os.path.abspath(os.path.dirname(
    __file__) + '/../vendor/') + '/')
if DEBUG:
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder')
COMPRESS_CSS_FILTERS = ['compressor.filters.cssmin.CSSCompressorFilter']
COMPRESS_STORAGE = 'compressor.storage.GzipCompressorFileStorage'
COMPRESS_OFFLINE = not DEBUG
