def add_routes(app, secret_key):...
handle_html.timeout = app['ini'].getint('sessions', 'session_idle_timeout')
cache_page.timeout = app['ini'].getint('sessions', 'cached_page_timeout')
app.router.add_get('/', GET_index)
app.router.add_get('/index', GET_index)
app.router.add_get('/login', GET_login)
app.router.add_post('/login', POST_login)
app.router.add_get('/settings', GET_settings)
app.router.add_post('/settings', POST_settings)
app.router.add_get('/mapmaker', GET_mapmaker)
app.router.add_get('/map', GET_map)
app.router.add_get('/mazetest', GET_test)
app.router.add_static('/static/', path='static', name='static')
session_setup(app, EncryptedCookieStorage(secret_key))
