def test_authentication_error(self):...
"""docstring"""
test = self
calls = []
def failing(request):...
def skipped(request):...
self.fail('authenticate should not be called')
@classmethod...
return [failing, skipped]
