def suspending_receiver(signal, **decorator_kwargs):...
"""docstring"""
def our_wrapper(func):...
@receiver(signal, **decorator_kwargs)...
if settings.SUSPEND_SIGNALS:
return
return func(sender, **kwargs)
