def test_add_message(self):...
req = EngineAuthRequest.blank('/auth/google')
req._load_session()
msgs = req.get_messages()
self.assertEquals(msgs, None)
req.add_message('TEST MESSAGE')
msgs = req.get_messages()
self.assertEquals(msgs, [{'level': None, 'message': 'TEST MESSAGE'}])
msgs = req.get_messages()
self.assertEquals(msgs, None)
req.add_message('TEST1', 'error')
req.add_message('TEST2', 'success')
msgs = req.get_messages()
self.assertEquals(msgs, [{'level': 'error', 'message': 'TEST1'}, {'level':
    'success', 'message': 'TEST2'}])
msgs = req.get_messages()
self.assertEquals(msgs, None)
req.add_message('TEST1', 'error')
req.add_message('TEST2', 'success', '_mykey')
msgs = req.get_messages()
self.assertEquals(msgs, [{'level': 'error', 'message': 'TEST1'}])
msgs_key = req.get_messages('_mykey')
self.assertEquals(msgs_key, [{'level': 'success', 'message': 'TEST2'}])
msgs = req.get_messages()
self.assertEquals(msgs, None)
msgs_key = req.get_messages()
self.assertEquals(msgs_key, None)
