def add_localizer_to_request(event):...
request = event.request
localizer = get_localizer(request)
def auto_translate(*args, **kwargs):...
return localizer.translate(translation_string_factory(*args, **kwargs))
