def __init__(self, *args, **kwargs):...
super().__init__(*args, **kwargs)
self.setup_logging()
self.setup_window()
self.setup_menus()
self.setup_action_listeners()
self.setup_log_window()
self.setup_matisse()
self.setup_widgets()
self.aboutToQuit.connect(self.clean_up)
container = QWidget()
container.setLayout(self.layout)
self.window.setCentralWidget(container)
self.window.show()
