import asyncpg
def __init__(self, db_conn):...
self.db_conn = db_conn
async def fetch_user_info(self, member_id: int, column: str):...
query = f'SELECT {column} FROM user_info WHERE member_id = {member_id};'
return await self.db_conn.fetchval(query)
