def test_course_instance_get_visible(self):...
open_course_instances = CourseInstance.objects.get_visible()
self.assertEqual(3, len(open_course_instances))
self.assertTrue(self.current_course_instance in open_course_instances)
self.assertTrue(self.future_course_instance in open_course_instances)
open_course_instances = CourseInstance.objects.get_visible(self.user)
self.assertEqual(3, len(open_course_instances))
self.assertTrue(self.current_course_instance in open_course_instances)
self.assertTrue(self.future_course_instance in open_course_instances)
open_course_instances = CourseInstance.objects.get_visible(self.superuser)
self.assertEqual(4, len(open_course_instances))
self.assertTrue(self.current_course_instance in open_course_instances)
self.assertTrue(self.future_course_instance in open_course_instances)
self.assertTrue(self.hidden_course_instance in open_course_instances)
