def set_steps_at_least(achievement_id, player_id, steps):...
steps_function = lambda current_steps, new_steps: max(current_steps, new_steps)
return update_steps(achievement_id, player_id, steps, steps_function)
