def add_comment(self, t, msg):...
if True:
self.postmsg(t[1], msg, t[0])
self.counters['comments'] += 1
self.w.sleep(self.comment_successtimeout)
self.w.sleep(self.comment_successtimeout)
self.schedule(self.add_comment, (t, msg))
self.targets.remove(t)
self.w.sleep(self.comment_successtimeout)
self.log.error('Too many wrong answers to CAPTCHA')
self.schedule(self.add_comment, (t, msg))
self.log.warn('%s: %s', e, e.answer)
self.schedule(self.add_comment, (t, msg))
self.schedule(self.add_comment, (t, msg))
self.schedule_first(self.switch_user)
self.log.info('Removing %s from targets', t)
self.targets.remove(t)
self.w.sleep(self.errortimeout)
self.schedule(self.add_comment, (t, msg))
self.w.sleep(self.errortimeout)
self.targets.remove(t)
self.w.sleep(self.errortimeout)
self.log.exception(e)
self.w.sleep(self.errortimeout)
