from . import *
from .wzbase import WZBase
def __init__(self):...
self.req_handlers = {}
self.response_handlers = {}
self.sig_handlers = {}
self.iden_reqid_map = BijectiveSetMap()
def set_req_handler(self, interface, method, fun):...
self.req_handlers[interface, method] = fun
def set_response_handler(self, reqid, fun):...
self.response_handlers[reqid] = fun
def set_sig_handler(self, interface, method, fun):...
self.sig_handlers[interface, method] = fun
def del_req_handler(self, interface, method):...
def del_response_handler(self, reqid):...
def del_sig_handler(self, interface, method):...
def _parse_req(self, iden, msg, reqid, interface, method):...
handler = self.req_handlers[interface, method]
if iden:
handler = self.req_handlers[interface, None]
self.iden_reqid_map.add_value(tuple(iden), reqid)
handler(reqid, interface, method, msg[1:])
return ()
