def test_course_teacher_views(self):...
url = self.current_course_instance.get_edit_url()
response = self.client.get(url)
self.assertEqual(response.status_code, 302)
self.client.login(username='testUser', password='testPassword')
response = self.client.get(url)
self.assertEqual(response.status_code, 403)
self.current_course_instance.assistants.add(self.grader.userprofile)
self.client.login(username='grader', password='graderPassword')
response = self.client.get(url)
self.assertEqual(response.status_code, 403)
response = self.client.get(self.current_course_instance.get_absolute_url(),
    follow=True)
self.assertEqual(response.status_code, 200)
self.assertTrue(response.context['is_assistant'])
self.assertFalse(response.context['is_teacher'])
self.current_course_instance.assistants.clear()
self.course.teachers.add(self.grader.userprofile)
response = self.client.get(url)
self.assertEqual(response.status_code, 200)
response = self.client.get(self.current_course_instance.get_absolute_url(),
    follow=True)
self.assertEqual(response.status_code, 200)
self.assertFalse(response.context['is_assistant'])
self.assertTrue(response.context['is_teacher'])
self.client.logout()
response = self.client.get(url)
self.assertEqual(response.status_code, 302)
self.client.login(username='staff', password='staffPassword')
response = self.client.get(url)
self.assertEqual(response.status_code, 200)
self.assertFalse(response.context['is_assistant'])
self.assertTrue(response.context['is_teacher'])
