def get_awaiter_for_event(self, event, condition=lambda msg: True, **kwargs):...
if self.closed:
result = {'msg': None}
def match(msg):...
result['msg'] = msg
return msg.type == 'event' and msg.event == event and condition(msg)
