def test_get_peer_host(self):...
@api.public...
self.response.write(api.get_peer_host() or '<none>')
app = self.make_test_app('/request', Handler)
def call(headers):...
api.reset_local_state()
return app.get('/request', headers=headers).body
