def test_cluster_proxy_stale_revision(self):...
def stale_revision():...
api = self.mock_nsx_clustered_api(session_response=stale_revision)
self.assertRaises(nsxlib_exc.StaleRevision, api.get, 'api/v1/transport-zones')
