def test_when_called_redirect_view_redirects_to_apps_url(self):...
RedirectLoginEmailTestCase.ScenarioMaker().when_call_login_email_redirect(
    ).then_response_should_be_a_redirect_to_app_deeplink_with_params()
